### ISSUE TITLE
getNode method doesn't return valid results

### ISSUE THREAD

**Issue by nicolasfagotti** [Netflix/vizceral#103]
The [getNode method](https://github.com/Netflix/vizceral/blob/master/USAGE.md#getnode) doesn't return a valid result when the node requested is not from the first level.

A request like getNode([firstLevelNode]) returns the correct node, but getNode([firstLevelNode, secondLevelNode]) request returns undefined.

**Comment by jrsquared** [comment]
Fixed by #104
