### ISSUE TITLE
Donuts circumferences not coloured

### ISSUE THREAD

**Issue by nicolasfagotti** [Netflix/vizceral#105]
Hi,

It's just me or the donuts circumferences are not correctly coloured since version 4.5.x? The issue is visible by just updating the vizceral example with a newer version:
### v4.4.3
![vizceral_v4 4 3](https://user-images.githubusercontent.com/922783/32738803-c779ac02-c87c-11e7-9a66-e420b1fcc592.png)
### v4.5.5
![vizceral_v4 5 5](https://user-images.githubusercontent.com/922783/32738820-d5d165a6-c87c-11e7-8ea7-f0bbfe1477d8.png)

**Comment by jlew** [comment]
I see it as well.

**Comment by javafuns** [comment]
this regression was introduced by commit 480b5bb4701f847e24e16cfd03f3eadad2944ad9

**Comment by jrsquared** [comment]
Fixed in 4.7.2
