### ISSUE TITLE
Why is there so many duplicate point warn in my project?And this will make the computer's CPU very high?

### ISSUE THREAD

**Issue by yinbowen** [Netflix/vizceral#109]
![wechatimg65](https://user-images.githubusercontent.com/7412410/34248965-e0d892ee-e672-11e7-810d-d842f43753e1.jpeg)

**Comment by yinbowen** [comment]
This page also takes up very high memory. What can I do?
![wechatimg67](https://user-images.githubusercontent.com/7412410/34249831-0be75396-e676-11e7-94b4-f7a8c81a2d1d.jpeg)

**Comment by manico** [comment]
Yup. I takes almost all of CPU.
Is there anything we can do to optimize this?

**Comment by jrsquared** [comment]
The duplicate points are not the cause of the high CPU. The use of WebGL is the cause of the high CPU. Closing this as the duplicate points are a part of the #93 and the high CPU is currently a fact of life unless someone wants to work on optimizations and open a PR.
