### ISSUE TITLE
Custom shapes for nodes (pull #93) source of trouble

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral#112]
So I just got around to catching up my local stuff with the latest commits and there are several issues derived from pull #93. 

It is also the cause of issue #109.  It works only for the new shapes.  It is broken in several ways all tied to using the standard (default) shape... circles.

- The code style is not consistent (some ES6 class, some not), delicate dependence on `this` in `ShapeParent`'s constructor.
- It can't generate the hole to cut out the center of a node any more.
- The ability to pass a radius or size to a node, which means that pull #111 is likely to have trouble. Has been lost.  The only location still using a passed radius/size is for setting the notice dot geometry.

## `ShapeParent` and the rest
The whole structure of how the shapes aren't using their own constructor or calling `super` but instead import `ShapeParent` and making use of `ShapeParent`'s constructor.  Of which `ShapeParent`'s constructor makes a call to `_createInnerGeometry(...)`, which is not be defined in `ShapeParent` at all but is entirely dependent on it existing as a method of the right `this` being the active scope when evaluated.  It's fragile and bound for trouble since.  It may have been redundant, but it was a lot more readable and robust when the shapes each had their own constructor.  I mean the exact same `_createMaterial` is in every single shape file, so even the removal of duplicate functions to `ShapeParent` isn't uniform.

## Broken "default" node shape
The massive number of duplicate point warning is because the hole cutout wasn't copied correctly from `NodeView`.  It should be simply
```javascript
    const circleShape = new THREE.Shape();
    circleShape.absarc(0, 0, radius, 0, 2 * Math.PI, false);
    const holeShape = new THREE.Path();
   /* Was wrong, because the hole's radius was the same as the shape's.
       It has to be smaller to make a hole. */
    holeShape.absarc(0, 0, radius -2, 0, 2 * Math.PI, true);
    circleShape.holes.push(holeShape);
    return new THREE.ShapeGeometry(circleShape, curveSegments);
```
This will eliminate the `THREE.ShapeUtils` "Duplicate Points" warnings, but even then `_createMaterial()` throws a number of warnings because `color` is undefined.   This is because there is no `GlobalStyles.styles.colorShapeBorder`.   As a side note it would be more inline with the current methodology for getting colors to create a `getNodeStatusColor` and a `getShapeBorderColor` (assuming the missing colorShapeBorder is added/described by the author/authors, since it is.

Even then, things are still messed up because pull #93 completely dropped the [`innerCircleGeometry`](https://github.com/Netflix/vizceral/blob/b88e62bcd7a798521e0e42a3542772b64c81a50d/src/base/nodeView.js#L225) and replaced it with the equivalent of [`innerBorderGeometry`](https://github.com/Netflix/vizceral/blob/b88e62bcd7a798521e0e42a3542772b64c81a50d/src/base/nodeView.js#L234) which means you can see particles waiting to be launched and the particles disappearing at the end.

## Loss of ability to pass in a radius/size for a node
The ability to pass in the radius/size of a node has been completely eliminated, except for one sketchy remnant where the [notice dot size](https://github.com/Netflix/vizceral/blob/master/src/base/nodeViewStandard.js#L42) can still make use of a passed in radius, instead of the hard coded value in [`ShapeDefault`](https://github.com/Netflix/vizceral/blob/master/src/base/shapes/ShapeDefault.js).  I suspect that if a radius were passed in that is 16 or greater the results would be quite unexpected.

## Code Style and simple testing
Then `ShapeFactory` is a class that isn't using ES6 syntax like all previous Vizceral work.
`ShapesUtils` is also a class that isn't ES6 style like the rest of Vizceral.  It is also confusing as the errors in `ShapeDefault` cause THREE to through hundreds of "Duplicate point" warning from `THREE.ShapeUtils`.  It would be cleaner if it had a different name, even it it was just to spell "utilities" out completely to help differentiate from the THREE class.

I know it sounds like I'm just whining and moaning, but I'm all for the custom node shapes.  I had written my own version of this and it is not extensible like pull #93's at is... but pull #93 was definitely not given the simple test of using `vizceral-example` as a quick check that it doesn't break anything.

The visuals of the default nodes needs to be unchanged (colors, geometries).  The ability to change the radius needs to be maintained not lost.  The long term maintainability and coding style that has been followed need to be used so that more shapes can be added and there isn't the inherit risk that the wrong `this` will be scoped.  Finally, there shouldn't be any tidal wave off warnings produced.  THREE eventually declares it is in an infinite loop and bails due to the errors in the default shape class, followed closely by trying to use of a color from `GlobalStyles` that has never been defined.

All this is why I submit that pull #93 be reverted until these issues are addressed and to allow existing necessary behavior to be restored until this excellent feature is tested and safe for use by developers other than its creator(s).

**Comment by jrsquared** [comment]
Oh man, thank you for such a thorough review; it is definitely not whining. It is honestly my fault for not giving #93 a thorough testing and just testing the PR branch.  I haven't been fully around for a couple months. I will look into this and revert it when I'm back at a usable computer. In the meantime, @vshamgin can you respond to this?

**Comment by vshamgin** [comment]
“It can't generate the hole to cut out the center of a node any more.” - yes you can. The shape “service” is using a cut hole for example. With Three.js (or any other 3D software) the order (CCW/CW) of closing a shape or polygon is different: one will look transparent, the other is not. The transparent hole will not cut a hole.

**Comment by vshamgin** [comment]
“be reverted until these issues are addressed and to allow existing necessary behavior to be restored“ if you look at the code, if node shape is not specified, the default node will be loaded as it was before, there is nothing to “restore”

**Comment by vshamgin** [comment]
“The ability to pass a radius or size to a node, which means that pull #111 is likely to have trouble. Has been lost” - radius makes sence when all nodes are circular, if a node is a rectangle, I would recommend to use something like “scale factor”. I agree, this part of code could be optimized

**Comment by vshamgin** [comment]
“It's fragile and bound for trouble since. It may have been redundant, but it was a lot more readable and robust when the shapes each had their own constructor” - the constructor of each Shape class was used to do the same thing: to call for material creation, shape creation and border creation. Other than that it wad not used for anything else; thats why I am using the parent’s constructor. Any ideas? I would also ‘d like to see the example of a potential trouble with this. Thanks.

**Comment by vshamgin** [comment]
I will be looking into “warning” issue. Thank you!

**Comment by vshamgin** [comment]
@jrsquared @aSqrd-eSqrd

**Comment by aSqrd-eSqrd** [comment]
@vshamgin 
Thanks for the responses.

I was only testing the "default" (no `node_type` supplied) shape generation.  It is in the default shape that has the bulk of the issues.  In `ShapeDefault` in the `_createInnerGeometry ()` function the holeShape is constructed with the exact same radius as the 
```javascript
circleShape.absarc(0, 0, radius, 0, 2 * Math.PI, false);
\\...
holeShape.absarc(0, 0, radius, 0, 2 * Math.PI, false); \\ Same radius as circleShape !!!!
```
This causes all the warnings from `THREE ShapeUtils` about duplicate points, infinite loops and holes outside of the shape.

Also, still in `ShapeDefault` the `_createInnerGeometry` doesn't have any input arguments, even though the ShapeParent calls it with a radius and curve segments arguments... granted they are all hard coded.

I agree that conceptually `ShapeParent` is a nice setup, but it does it really help?  When, if ever would the `_createOuterBorder` function in `ShapeParent` ever be called?  It scares me that it calls `this._createInnerGeometry` which is not defined inside `ShapeParent`, but comes from `this`.  So if I make a new shape to add to the factory and it doesn't have a `_createInnerGeometry` it will break.

Maybe, I'm just being overly nervous about having the constructor in `ShapeParent` calling functions defined in other classes that may or may not exist via `this`.  Since `_createInnerGeometry` and `_createOuterBorder` are all coming from their respective shape class, the only thing in `ShapeParent` that I can tell is really doing is anything is the call to `_createMaterial` that creates the `THREE.MeshBasicMaterials` and the instantiation of the `customNode` object.  It isn't really creating the `THREE.Shape` geometries or even "connecting" the geometries and materials together, as that happens in `NodeViewStandard`.

`ShapeParent` is also the source of the other THREE warnings since it tries to use a non-existent color from `GlobalStyles`, `GlobStyles.styles.styles.colorShapeBorder`.

Each shape is so unique is it really hurting to have each with its own constructor similar to the way it was in c8aec1b?  Granted, it would need your `nodeStatus` `if-else` added to select the appropriate color.

We do need to keep the ability to pass in radius as an argument to the circles/default shape.  Though, this is something @jrsquared should look at because it is confusing what is going on with `node.size` and `node.radius`.  For example,  in `FocusedNodeView`  `node.size` (`this.object.size` in this case) is used to set the radius of the view.  The same occurs in `DnsNodeView` too.  But the actual `this.radius` from in `NodeViewStandard` is used to set the Notice dot size and was used to set the actual node circles' geometry as well.  What I'm trying to say is we still need to be able to pass in a radius to set the sizes of the circle's geometry... eventually it would be good to accept the geometry radius as an input to the constructor, but that is outside the scope of this discussion...
Also, since the radius is still being used by the Notice dot and not the `ShapeFactory` you can end up with fun stuff like this (this is using the current shape code by the way).  Notice how it effected the positioning of the label too, that's weird.

| radius = 16 | radius = 50 |
|:----:|:----:|
| ![image](https://user-images.githubusercontent.com/23126967/34616508-7fb72008-f206-11e7-9795-6c1e024b0d6d.png) | ![image](https://user-images.githubusercontent.com/23126967/34619238-860ad77a-f20f-11e7-9512-e3d106c1fe30.png) |


There is still the issue of the loss of the `innerCircleGeometry` from `NodeViewStandard`.  This is a critcal piece of the circle shapes.  Below, is my table of screenshots for the expected circle behavior, the current, and the current with the hole radius issue fixed.  By "Fixed Hole Issue" I mean I did the following in `ShapeDefault`
```diff
-holeShape.absarc(0, 0, radius, 0, 2 * Math.PI, false);
+holeShape.absarc(0, 0, radius - 2, 0, 2 * Math.PI, false);
```

|Expected | Expected w/ Notice | Expected & Class is Warning |
|:----:|:----:|:---:|
| ![image](https://user-images.githubusercontent.com/23126967/34617492-a0cbbb98-f209-11e7-8dec-2f95802425be.png) | ![image](https://user-images.githubusercontent.com/23126967/34617416-58c91ad4-f209-11e7-9c8b-5e65fff00dae.png) | ![image](https://user-images.githubusercontent.com/23126967/34617871-c7cee1b0-f20a-11e7-8621-0ab5ee137cf2.png) |
| **Current** | **Current w/ Notice** | **Current & Class is Warning** |
![image](https://user-images.githubusercontent.com/23126967/34616508-7fb72008-f206-11e7-9795-6c1e024b0d6d.png) | ![image](https://user-images.githubusercontent.com/23126967/34616562-ac61b55a-f206-11e7-8cc5-93a2927e67da.png) | ![image](https://user-images.githubusercontent.com/23126967/34617808-954c3f30-f20a-11e7-99cc-6dfbb078f155.png) |
| **Current w/ Fixed Hole Issue** | **Current w/ Fixed Hole w/ Notice** | ** Current w/ Fixed Hole & Class is Warning |
| ![image](https://user-images.githubusercontent.com/23126967/34616388-1ca983a2-f206-11e7-91ef-ae4b8ffdfa9a.png) | ![image](https://user-images.githubusercontent.com/23126967/34617960-2d9e06e2-f20b-11e7-8603-7b7d4fb002a6.png) | ![image](https://user-images.githubusercontent.com/23126967/34618000-5762af6e-f20b-11e7-8d38-725de41325c0.png) |

Well, this is a lot to read through as one big blob of text... sorry about that.  I'll be interested to here your @vshamgin and @jrsquared thoughts/opinions on the `ShapeParent` stuff.  After all, my concerns with that are purely my subjective opinion based on my struggle to figure out what was going on and which `THREE.Shape` creation function was actually being used.

**Comment by jrsquared** [comment]
It definitely sounds like there was an issue introduced... Thank you for the detailed writeup! I don't have time these days unfortunately to dig in, but happy to look at any PRs to fix this...

**Comment by jrsquared** [comment]
Reverted the PR that caused these issues, so will close this.
