### ISSUE TITLE
need to integrate in java project

### ISSUE THREAD

**Issue by apatnaik1** [Netflix/vizceral#118]
Hello Team,

I want to integrate this code in java web application for that. i need js files.

can you give me the code or document in simple js files

**Comment by aSqrd-eSqrd** [comment]
Umm, it already is pure JS.

**Comment by apatnaik1** [comment]
where can i get js file

**Comment by millette** [comment]
@apatnaik1 See the [Getting Started](https://github.com/Netflix/vizceral/wiki/Getting-Started) page on the wiki.

**Comment by apatnaik1** [comment]
I need more functions to customize my project.
