### ISSUE TITLE
Clarity on the UpdateData

### ISSUE THREAD

**Issue by arijoon** [Netflix/vizceral#120]
I've read most of the docs and played with the example project, one thing that is still unclear to me is the updateData part. Do you have to reconstruct the entire node/connection graph with updated number and then send that in or can you feed partial info, e.g. { normal: 1, warn: 1 from: "nodeA", to: "nodeB" }, while keeping everything else? and have that just visualize 1 particle and then stop as opposed to keep simulating until new data sets it to 0.

**Comment by jrsquared** [comment]
You have to send it the entire data structure every time and it will always visualize/simulate the level of traffic that is sent in until new data is sent.
