### ISSUE TITLE
More than 2 hops

### ISSUE THREAD

**Issue by maskaiitd** [Netflix/vizceral#121]
Hi 
Can we have more than 2 hops like
Global -> Region -> VPC -> Instances
not restricting to Global -> Region

**Comment by jrsquared** [comment]
Yes.

https://github.com/Netflix/vizceral/wiki/How-to-Use#graph-data-format

**Comment by andrewfrancisque** [comment]
@jrsquared, @maskaiitd, can you provide an example please?
