### ISSUE TITLE
What determines drawing of the connection line

### ISSUE THREAD

**Issue by arijoon** [Netflix/vizceral#122]
What determines the drawing of the connection line? e.g. I have majority of connections sending particles to each other but no connection line. Is there a specific requirement that triggers the drawing of a connectionline? 

also I was unable to find documentation for custom layouts, are there any examples to make the services draw in a specific order?

**Comment by jrsquared** [comment]
If you are using one of the built in connection types, they inherit from `ConnectionView` which will draw a line. https://github.com/Netflix/vizceral/blob/master/src/base/connectionView.js#L246-L248

If you are creating your own custom layout with a custom connection, you will have to draw a connection yourself.

There is no explicit documentation for custom layouts, but if you just look at the existing ones, it should more or less show how a new one will need to be built.
