### ISSUE TITLE
RegionNode style

### ISSUE THREAD

**Issue by Hollymingyi** [Netflix/vizceral#125]
can somebody help me to resize the region node size?

**Comment by jrsquared** [comment]
If you want a different size, you can pass in the size in the traffic graph json https://github.com/Netflix/vizceral/blob/master/src/region/regionNode.js#L24

**Comment by Hollymingyi** [comment]
ok,thks

2018-05-29 2:27 GMT+08:00 Justin Reynolds <notifications@github.com>:
