### ISSUE TITLE
Curved connections between nodes

### ISSUE THREAD

**Issue by franpog859** [Netflix/vizceral#132]
Hey! Is there a possibility to implement curved connections between nodes? Sometimes there are more than one connection between two nodes and I don't know how to show it. Connections overlap each other and we can't really see each of them.
This idea came to my mind and I don't know if it will be hard to implement. Maybe you have some other idea?

**Comment by carte7000** [comment]
Hi @franpog859, earlier this year I had to work on something similar. Basically I added a "magnitude" parameter to the connection which specify the sharpness of the curve. You can see what I have done here https://github.com/carte7000/vizceral/blob/59f3e26e28b449689cba23bace0661d855e5cf1c/src/base/connectionView.js#L518

It is definitly not ready to be merged in the official repo, but you can take a look and maybe we can make that happen together :)

**Comment by franpog859** [comment]
Thanks, @carte7000 ! Your idea with the Bezier curve helped me a lot! 
I think I need to dive a little bit more into the Vizceral and the Three library. If I do I will definitely take part in it ;)

**Comment by jrsquared** [comment]
If you look at https://github.com/Netflix/vizceral/blob/master/src/dns/dnsConnectionView.js, we created and used curved connections for that view.
