### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by RafaelHenriques** [Netflix/vizceral#133]
I think the tutorial is not complete. Where can I put the code for run? All the code is completed?

**Comment by franpog859** [comment]
This is an example of this library usage - https://github.com/Netflix/vizceral-example
Vizceral itself is put in the [`trafficFlow.js`](https://github.com/Netflix/vizceral-example/blob/master/src/components/trafficFlow.jsx) file.
Many settings are explained in the [Wiki](https://github.com/Netflix/Vizceral/wiki/Getting-Started).

I think that is all you need to start developing your app 😉

**Comment by jrsquared** [comment]
Thank you @franpog859!
