### ISSUE TITLE
vizceral.js:formatted:37091 Uncaught TypeError: r.setValue is not a function  : Upgrading to 4.7.0 version.

### ISSUE THREAD

**Issue by jsamireddy** [Netflix/vizceral#138]
We have recently upgraded from version 4.6.0 to 4.7.0. After the upgrade we are seeing the following error in the browser console. The vizceral graph is not rendering either and the browser is stuck in an infinite loop.

vizceral.js:formatted:37091 Uncaught TypeError: r.setValue is not a function
    at Kn.setValue (vizceral.js:formatted:37091)
    at Ut (vizceral.js:formatted:37091)
    at _r.renderBufferDirect (vizceral.js:formatted:37091)
    at Bt (vizceral.js:formatted:37091)
    at Dt (vizceral.js:formatted:37091)
    at _r.render (vizceral.js:formatted:37091)
    at e.value (vizceral.js:formatted:1)
    at e.value (vizceral.js:formatted:1)

This issue only happens if i set the webpack mode to production. When running is development mode there are no issues.

**Comment by jsamireddy** [comment]
I have tried my best to debug this in vizceral without any success. I had upgraded webpack versions to match the versions in vizceral.

**Comment by jrsquared** [comment]
Let me know if v4.7.3 fixes it for you. Looks like it might be a minification problem with the newest version of uglify that webpack 4 uses?

**Comment by jsamireddy** [comment]
Upgrading to 4.7.3 version has resolved the issue. Thank you very much for the quick update.
