### ISSUE TITLE
What's the roadmap for Vizceral features / additions for the foreseeable future?

### ISSUE THREAD

**Issue by parthms** [Netflix/vizceral#16]

**Comment by jasonwr** [comment]
@parthms Do you have a specific issue or feature request?

**Comment by parthms** [comment]
@jasonwr - I was wondering if you were going to allow the selection of edges / connections instead of just nodes, allow positioning nodes, and have the ability to use icons for nodes / instances?

**Comment by jrsquared** [comment]
@parthms 

* I will be working on connection interactivity in the near future.
* There are no plans currently for interactive positioning of nodes.  At some point, I want to make the layout worker pluggable so you would be able to write your own layout algorithm, which would allow you to position the incoming nodes however you like.
* There are no plans to use icons for nodes, but that is an interesting idea...

**Comment by parthms** [comment]
@jrsquared - Thanks for such a quick reply. And great job with Vizceral! Love it.

**Comment by jrsquared** [comment]
Thanks!
