### ISSUE TITLE
Trouble creating a minimum example

### ISSUE THREAD

**Issue by gphat** [Netflix/vizceral#3]
First off, thanks for you recent talk at Monitorama about Visceral and also thanks for making it available as Open Source!

I'm attempting to evaluate Visceral, but I'm having trouble finding a minimum example that gives me all the features.

The [DATAFORMATS.md](https://github.com/Netflix/vizceral/blob/master/DATAFORMATS.md) example emits a lot of warnings (because a `"class": "normal"` needs to be on the `us-west-2` node and then it just sits and never displays anything:

<img width="236" alt="screenshot 2016-07-01 22 11 24" src="https://cloud.githubusercontent.com/assets/45159/16537956/cb597862-3fd8-11e6-93b8-3fa5ad27f41c.png">

Here's the JSON I got after copying and properly formatting the `DATAFORMATS.md` example:

```json
{
  "renderer": "global",
  "name": "edge",
  "nodes": [
    {
      "renderer": "region",
      "name": "us-west-2",
      "class": "normal",
      "updated": 1462471847,
      "maxVolume": 100000,
      "nodes": [
        {
          "name": "INTERNET"
        },
        {
          "name": "apiproxy-prod",
          "notices": [
            {
              "title": "Notice about something",
              "link": "http://link/to/relevant/thing",
              "severity": 1
            }
          ],
          "class": "normal",
          "metadata": {},
          "nodes": [],
          "connections": []
        }
      ],
      "connections": [
        {
          "source": "INTERNET",
          "target": "apiproxy-prod",
          "metrics": {
            "normal": 5000,
            "danger": 5,
            "warning": 0
          },
          "notices": [
            {
              "title": "Notice about something",
              "subtitle": "Subtitle",
              "link": "http://link/to/relevant/thing",
              "severity": 1
            }
          ],
          "metadata": {},
          "class": "normal"
        }
      ]
    }
  ]
}
```
The sample_data included in the React component works fine, but it's really, really large and very difficult to get a sense of what's there. I've managed to make my own that works, but has no particle drawing.

```json
{
  "renderer": "global",
  "name": "edge",
  "nodes": [
    {
      "renderer": "region",
      "name": "INTERNET",
      "updated": 1466838417510,
      "nodes": [
      ],
      "class": "normal"
    },
    {
      "renderer": "region",
      "name": "us-east-1",
      "class": "normal",
      "updated": 1466838546805,
      "nodes": [
        {
          "name": "INTERNET",
          "class": "normal"
        },
        {
          "name": "proxy-prod",
          "metadata": {
            "streaming": true
          },
          "class": "normal"
        }
      ],
      "connections": [
        {
          "source": "INTERNET",
          "metadata": {
            "streaming": true
          },
          "metrics": {
            "danger": 0.646,
            "normal": 31.12
          },
          "class": "normal"
        },
        {
          "source": "INTERNET",
          "metadata": {
            "streaming": true
          },
          "metrics": {
            "danger": 0.582,
            "normal": 218.972
          },
          "class": "normal"
        },
        {
          "source": "INTERNET",
          "metadata": {
            "streaming": true
          },
          "metrics": {
            "normal": 11.072
          },
          "class": "normal"
        },
        {
          "source": "INTERNET",
          "target": "proxy-prod",
          "metadata": {
            "streaming": true
          },
          "metrics": {
            "danger": 116.524,
            "normal": 15598.906
          },
          "status": {
            "danger": 281.33,
            "normal": 65364.56
          },
          "class": "normal"
        }
      ]
    }
  ],
  "connections": [
    {
      "source": "INTERNET",
      "target": "us-east-1",
      "metrics": {
        "normal": 26037.626,
        "danger": 92.37
      },
      "notices": [

      ],
      "class": "normal"
    }
  ]
}
```
I thought perhaps not having `maxVolume` was the reason, but when I try and add it things just silently fail.

Can you perhaps provide or help me create a minimal configuration that demonstrates all the necessary parts to make this work? I'm happy to help, guinea pig or other wise chip in.

Thanks again!

**Comment by gphat** [comment]
I should add that I'm playing around with this via `visceral-example` by modifying `sample_data.json`. Happy to move this issue there is it's more appropriate!

**Comment by jrsquared** [comment]
Good catch. I have updated this repo with better maxVolume handling and proper error messaging if it is missing. I also updated the `vizceral-example` repo with the simple sample data structure that you pasted here (with the addition of the maxVolume property).  Please let me know if this fixes your concerns and if there is anything else I can (or should) do to make this easier to reason about.

**Comment by gphat** [comment]
Thanks @jrsquared! I'll review this in a bit and see if it all works, then report back.

**Comment by gphat** [comment]
Thanks @jrsquared for the quick action. I can confirm that the smaller file works for me once I realized I needed to change the source to use it (per your change back to the default). The default one is definitely a better demo, and the `simple` now provides an easier starting point. Thanks!
