### ISSUE TITLE
Method missing

### ISSUE THREAD

**Issue by ksoftirqd** [Netflix/vizceral#30]
It seems like method `setHighlightedObject` is missing. It is used in [zoomOutViewLevel](https://github.com/Netflix/vizceral/blob/31e36e993eeea9acfcffa990000fa6b972833c12/src/vizceral.js#L489)

[](url)
Could it be `this.currentGraph.highlightedObject(undefined)` instead?

**Comment by ksoftirqd** [comment]
It seems like the method is still undefined (`setHighlighted` methods are defined only for node/connection).

**Comment by jrsquared** [comment]
Whoops! Should be good now.
