### ISSUE TITLE
Memory leak within canvas

### ISSUE THREAD

**Issue by jasonwr** [Netflix/vizceral#40]
This may be a core JavaScript issue but I have a bunch of Vizceral graphs that I'm loading one at a time via a drop down menu. The problem is when each graph loads, it sets the current Vizceral object to null in hopes of the JS garbage collector picking it up. There seems to be a memory leak, where the memory occupied by Vizceral is still present and this is eating up the browser memory. I am running on Mozilla Firefox 40 and I know this utilizes Spider Monkey as opposed to the V8 JS engine in Google Chrome. Thoughts? Is this a JS issue and not Vizceral related?

**Comment by jasonwr** [comment]
Did some more testing with the Chrome memory profiler and I'm seeing the memory increase during each new graph draw (graph update). I'm doing this (keep in mind Angular services keep state in memory):

```javascript

// Angular service:
this.viz = null;

this.updateVizceral = function(data) {
   this.remove();
   if (this.viz === null) {
      this.loadVizceral(data);
   } else {
      updateData(data);
   }
};

this.loadVizceral = function(data) {
   if (!angular.element('#graph').html( )) {
      var graph = "<canvas class='vizceral' id='graph'></canvas>";
      angular.element('#graph-parent').append(graph);
   }
   var canvas = angular.element('#graph');
   var canvasWidth = canvas.clientWidth;
   var canvasHeight = canvas.clientHeight;
   this.viz = new Vizceral.default(canvas);
   this.viz.updateData(data);
   this.viz.setView();
   this.viz.animate();
   resize(canvas, canvasWidth, canvasHeight);
};

this.remove = function() {
   if (this.viz) {
      this.viz = null; // mark as removed for garbage collector
   }
};
```

The native updateData(data) should never be invoked since remove sets this.viz to null. The updateVizceral gets invoked with new API data for the selected graph and updates (generates) a new Vizceral graph with the new graph data. The API data returned from our REST endpoint contains the nodes, edges, and graph name. This works for our UI but the memory leak is definitely present.

**Comment by jrsquared** [comment]
It appears you're trying to create and destroy vizceral objects.  I would not recommend reusing the same canvas for every different vizceral object. I would recommend destroying the canvas and creating a new canvas anytime you want to create a new vizceral object.

That being said, destroying and creating vizceral objects multiple times was never a use case we considered, so there will probably be some leftover WebGL shaders and textures hanging around that aren't getting cleaned up properly.

**Comment by jasonwr** [comment]
@jrsquared I appreciate your response. You can see my user case though right? If I have a bunch of disconnected graphs that must be displayed, then what would be a better approach? Rather than having every sub-graph on one large, canvas where the number of nodes will approach 300 and eat up a ton of of the CPU/GPU time, we found that isolating these subgraphs and allowing a user to select what graph to display from a drop down menu was most beneficial. It seems to me like you're use case is that you have a graph with at maximum 75 nodes, and that is the only graph you need to visualize correct? Is the graph cyclic? I'm just trying to get a sense for what kind of a foot this shoe (i.e. Vizceral) can fit. Also I am destroying the entire canvas from the DOM every time a user clicks on a new graph to display from the menu with:

```javascript
angular.element('#graph').remove(); // there is a canvas directive with the id of 'graph'
```

Essentially I'm just doing a massive tear down and reconstruct (redraw) of the graph based off of the new nodes and edges.

**Comment by jrsquared** [comment]
We have multiple graphs of 100-200 nodes, with another graph for each node being loaded into a single vizceral object. Effectively ~600 graphs that can be navigated between each other; very similar to vizceral-example, just larger.

That is very interesting.  They may be a memory leak when destroying vizceral and maybe it should have an explicit teardown function. Please let me know what you find!

**Comment by jasonwr** [comment]
I'm testing in Firefox 40 and Chrome 40. I have managed to get the graphs to load properly but each reload, slows down the animated tics between nodes and eventually Firefox cores. Seems like there's something or things lying around and I'll keep looking through it. I prefer Chrome to FF because of Chromes impressive memory profiling tools, but most of our users are using Firefox, so I may need to profile with Chrome and then reexamine Firefox.

**Comment by jasonwr** [comment]
@jrsquared How hard would it be to create an explicit teardown function? Perhaps have something so that we can do the following:

```javascript
this.remove = function() {
   if (this.viz) {
      **this.viz.teardown(); // explicitly tear down Vizceral WebGL objects**
      this.viz = null; // mark as removed for garbage collector
   }
   angular.element('#graph').remove();
};
```

**Comment by jrsquared** [comment]
It probably wouldn't be too difficult, I look forward to your pull request.

**Comment by jasonwr** [comment]
Ha! Well... I'll see if I can get around to it. I'm in grad school and have a bunch of other stuff going on. Can you cover it? ;-)

**Comment by aaronblohowiak** [comment]
Have no fear! The PR review process will help prevent you from `messing something up` :D  We look forward to the contribution.

**Comment by jasonwr** [comment]
@aaronblohowiak so far my time is maxed but yes if I do get around to it post grad school I'll check it out. I found for the time being that a page refresh on each click works for me. It's a bit sloppy and the user will notice a page reload but it does work. I'll have to put this ticket on my TODO list along with PhantomJS based unit tests with Karma and Gulp code coverage. :+1:
