### ISSUE TITLE
Nodes outside view port when physics layout enabled

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral#44]
It appears that when using the recently merged physics layout option @jbrekelmans that nodes can end up outside the view port of the canvas.

Using vizceral ver 4.2.1, vizceral-react ver 4.2.0, and vizceral-example commit 0a17500211f12130cffb4b88145ad503ca6169bc (Note: vizceral-example needs a version tick in package.json), and the sample_data.json that is in that same vizceral-example commit.

It seems that the physics based layout is "skipping" a updatePosition call or needs something like the recalculateOrbitSize() call that was added in 386ee4edfa145cb964d47704c24d29213f5bd96f in globalTrafficGraph.js, but has moved to the ringCenterLayout in the latest commit.

Thanks for all the fixes and improvements @jbrekelmans and @jrsquared.  My own work has seen immediate improved performance thanks to your efforts.

**Comment by aSqrd-eSqrd** [comment]
First, this issue #44 and issue #77 are one and the same.

Second, I think finally got a line on what the source of the issue is.  It isn't the size of the canvas, it is the field of view of the camera.  Since it is an [orthographic camera](https://threejs.org/docs/#api/cameras/OrthographicCamera) it doesn't actually have a field-of-view, but it does have a viewing frustum (see THREE.js's docs on OrthographicCamera).

At any rate, I was digging around in `vizceral-example` trying to figure out why if the details panel was open, that I could drag a node to position that is not visible when the panel closed.  I noticed that the camera's top and bottom frustum values changed when the side panel opened.  This is to preserve the aspect ratio... blah, blah, blah.

If we put a check in somewhere (?? not sure where it should live ??) that checks the positions of nodes against the camera's frustum dimensions we could find and push back into view nodes that have "fallen" off the edge of the frustum.
This leads to another thing I'm not sure how to address in that if we just push things that are beyond the edge of the frustum back into view that could cause things to be overlapping in the layout... so how do would/do you make it check the layout and/or re-layout?

Is calling an update going to work?  Would setting `classInvalidated` work?  I'm really over my head at this level.  I've been trying to add a new render to create background grid and trying to integrate it with the "update" cycle isn't going well.  I can only image this is even trickier.

Thought?  Suggestions?

**Comment by jrsquared** [comment]
@jbrekelmans wrote all the re-layout stuff and it's not something we use interally, so I'm pretty over my head with that part of the codebase as well. Since he hasn't been active or responding to this, I'm going to close this for now since it's not something we will be actively looking at. Happy to review any PRs related to this, or to reopen it if @jbrekelmans can address it.
