### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by voelzmo** [Netflix/vizceral#45]
Hey, thanks for vizceral, it's amazing tool which I love to use.
However, it has been pretty tricky to figure out what changed compared to the last release. Especially in situation where you e.g. released 4.2.3 and 4.3 on the same day. What lead to a micro bump followed by a minor bump? What were the breaking changes between say 3.x and 4.x?

Could you please maintain a changelog/releasenotes, so I don't have to dig through individual commits?

Thanks!

**Comment by jrsquared** [comment]
Yep, it's been on my list but not with the priority it should have. I'll make sure to at least do this going forward. Thanks for the reminder! Glad you're enjoying Vizceral.

**Comment by jrsquared** [comment]
Updated some of the more recent tags, will keep it up to date as releases come.
https://github.com/Netflix/vizceral/releases

**Comment by voelzmo** [comment]
Great, thanks!

**Comment by voelzmo** [comment]
Hey @jrsquared, I hate to get back to this, but could you shed some light on what's new in the 4.4 series? Thanks!

**Comment by jrsquared** [comment]
Yep, totally dropped the ball on this again. I'll throw up some release
notes.
