### ISSUE TITLE
Historical graph?

### ISSUE THREAD

**Issue by rore** [Netflix/vizceral#47]
Hi,

The screenshot in the blog post about the open source of Vizceral shows also a historical graph for each node ( https://2.bp.blogspot.com/-R3OvpmfJPAk/V5-ds9USmQI/AAAAAAAAAmE/ri3UgSwrcc8uw8hglR2rPWIiK5rFSJ-agCLcB/s1600/global%2Bgraph.png ).

Is there a way to enable it? (I've converted the example app to show our data - pretty cool thing by the way, thank you for this! - but that graph is not showing).

**Comment by jasonwr** [comment]
@rore are you seeing an JS logging in your web console? If you don't see it showing you should see some warnings.

**Comment by rore** [comment]
In the web console I see the following - 
There's one warning when the page loads: 
`THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.`

And on each data update there are a couple of warnings like this: 
`vizceral.js:70631 Attempted to create a connection from source node 'INTERNET' with a target node that does not yet exist: '...`
Which I guess are due to some data issue between my connections and nodes.

Is the example app supposed to show these graphs with the example data? Because I don't remember seeing them even when I ran it with the sample data included.

**Comment by jrsquared** [comment]
@rore No, the example app does not have these graphs, this is normal, and has nothing to do with console logging. The graphs that are in the screenshot are pretty heavily tied into Netflix internal workings and I haven't had a chance to clean it up yet.  The graphs with historical data use a completely different data source than the Vizceral data source.

That being said, the dimensions that are used to place the divs are emitted in the `nodeContextSizeChanged` event.  It's poorly documented (https://github.com/Netflix/vizceral/blob/master/USAGE.md#nodecontextsizechanged), but if you capture the event, you will see the dimensions used for all of the graphs, and you can implement your own graphs, placing them using the emitted dimensions.  Anytime the graph resizes, the event is emitted again with updated dimensions.

Hope this helps!

**Comment by rore** [comment]
Thanks!
