### ISSUE TITLE
Stacked nodes at the detail nodes zoom level,  entryNodeMap issue

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral#50]
There is an issue that I have finally traced back to a single root cause.

The issue is most obvious at the detail node "zoom" level, but may also exist in the region level, but I haven't specifically looked for it there.

The problem in the detail node zoom level is that all the nodes end up stacked on top of each other in the center.  It doesn't happen to every node that is drilled down to the detail zoom level.  This is the key.  It turns out that bi-directional nodes get eliminated from the `_enteryNodeMap` (created in ltrTreeGraph.js) and so never get a rank or position.

The issue is even worse if all of the incoming connections have a outgoing connection (i.e. are bi-directional) then none of the nodes get placed.  Every single one is stacked one on top of the other in the center.

I suggest that any that the source node of any incoming connection/edge should remain in the `_entryNodeMap` regardless of whether it is a bi-directional connect... but I don't know what the consequences might be.

I've created a JSON data set that shows three possible results you can get when going to node detail level.

Go into the `soup-sandwich` region view and drill into:
1. AAA -- this detail view is perfect, it also has NO bi-directional connections
2. ZOOM-ME -- this detail view is the worst case with all nodes stacked.  The "trigger" is that all of the incoming connections are bi-directional.
3. ZOOM-ME-2nd -- this detail view is half-and-half.  It has 2 incoming connections and only one is bi-directional, so only one node is stacked in the center.

Thanks!

***Rename file ending from TXT to JSON***
[bi-directional-cnct-example_v2_json.txt]  <-- **UPDATED**: to proper `focusedChild`, was just `focused`
[bi-directional-cnct-example_v2_json.txt](https://github.com/Netflix/vizceral/files/736921/bi-directional-cnct-example_v2_json.txt)

**Comment by aSqrd-eSqrd** [comment]
Ooops, forgot which dev system I was on and the JSON file I attached was still using the `render: focused`, replaced it with the proper `render: focusedChild`.... so if you have a bi-directional-cnct-example_json.txt you're going to need to take the "v2" version.

**Comment by jrsquared** [comment]
Should be fixed, was a little more hairy to fix... had to be smarter about when to force rank promotions since the rank can be messed up with circular dependencies. Let me know if it works for you!

**Comment by aSqrd-eSqrd** [comment]
Thanks so much for your help and support!!

That is delicate.

I've been working in the ltrTreeLayout code a lot lately and noticed something that looked like it might be useful for  I was curious.  In the ltrTreeLayout system in `index.js` there is that hard coded argument set to `entryNode: 'INTERNET'`.   I see that the `forcePrimaryRankPromotions` and `forceSecondaryRankPromotions` use it but what if we used it for carrying in the selected/double-clicked node's name?

Say changing `trafficGraph.js` to make the graph carry the focused node's name... something like
```javascript
  _relayout () {
    // Update filters
    const graph = { nodes: [], connections: [], focusedNode: this.name };
```
Then pass it down into the layouts via `this.layout.run(...)` and on down into `ltrTreeGraph.js`, where it could be used to find all the incoming entryNodes by filtering for edges where `edge.target` equaled the focused/double-clicked node and adding the `edge.source` for all the edges that is true for.

I've only spent time with the ltrTreeLayout code, so I have no idea if it holds up for the other layouts or even what the consequences on `forcePrimaryRankPromotions` and `forceSecondaryRankPromotions` might be.  I just remembered the commit message in 600600e about working towards removing INTERNET as only valid entry node.

Thoughts?  I've got it partially worked out for ltrTreeLayout, but I've been having to follow the name of the focused/double-clicked node around through the debugger to see how I could access it and how deep into the layout functions it propagates (stays in scope).

Thanks

**Comment by jrsquared** [comment]
The graph, in theory, should not need the entry node at all, that should be able to be figured out from the graph itself.

A focused node only makes sense for the focused graph, but that being said, the itrGraphLayout doesn't really make sense for the focused graph at all, since we know it's only one focused node and it's upstream and downstream dependencies.

It would make sense to create a new, very simple, layout algorithm for the focused node, then we don't have to work on trying to generalize a more complex layout algorithm for such a simple use case.
