### ISSUE TITLE
Extending vizceral

### ISSUE THREAD

**Issue by deejay1** [Netflix/vizceral#51]
Frankly I may have no idea what I'm doing, but it seems to me like vizceral installed from npm isn't exporting it's subclasses, therefore it's hard to write custom functionality like custom renderers without resorting to copying the entire vizceral codebase to my own project.

After several hours on the web I finally gave up and I'm writing this "issue", because maybe I'm doing something wrong, but trying to import something like the Connection class by doing `import Connection from 'Vizceral/base/connection';` (or variants of it) it always ends up with something like `Module not found: Error: Cannot resolve module 'Vizceral/base/connection'`

Exporting the specific classes from `vizceral.js` works but needs to change the upstream files in my own repo.
Is this intended behaviour or am I doing something wrong here?

**Comment by jrsquared** [comment]
None of the internal classes were exported.  I just exported all the base classes (the ones in src/base). This should hopefully satisfy your use case.  There is definitely more work that needs to be done to check to make sure the constructors are called with appropriate parameters and some documentation, but this should unblock you. Let me know if it works for you!

**Comment by deejay1** [comment]
Thanks for that, with Paweł's changes (who's sitting right next to me ;) we're more on track...
