### ISSUE TITLE
Required INTERNET node

### ISSUE THREAD

**Issue by Baransu** [Netflix/vizceral#55]
We're [using](https://github.com/erlanglab/erlangpl) Vizceral for displaying communication between nodes in cluster, and processes in node on Erlang VM. Because cluster can have internal communication without internet input/output is there possibility to replace required `INTERNET` node with any other node which can be clicked?

Maybe I missed some part about it in documentation. If it's not possible right now maybe you can point me into right direction with that so I can try to come up with some solution to this problem.

**Comment by Baransu** [comment]
Another thing is showing messages going to `INTERNET` node. Wile it's possible to show messages going in both directions between normal nodes, it's impossible to achieve the same result for `INTERNET` node.

**Comment by jrsquared** [comment]
There is an outstanding work item to remove any hardcoded logic around an entry node named `INTERNET`. However, if you do not have a node named `INTERNET` it still should work fine.

The only place that `INTERNET` is still hard coded is in the [ltrLayoutWorker](https://github.com/Netflix/vizceral/blob/master/src/layouts/ltrTreeLayout/index.js#L89) and the only thing that hardcoded field is [used for](https://github.com/Netflix/vizceral/blob/master/src/layouts/ltrTreeLayout/ranker.js#L59) is _if_ it exists, make it the only entry node.

If you have a specific example exhibiting this problem, please share it so I can help debug what is happening.

**Comment by Baransu** [comment]
We dont have any troubles around it because we're just naming about main (observed) node as Internet. We're having more troubles with showing messages goint in two directions and making this node clickable

**Comment by Baransu** [comment]
I've just raised this issue because it would be nice to create any infrastructure without false naming, selecting only one node as 'root' node.

**Comment by jrsquared** [comment]
I completely agree that the behavior you describe is undesirable. If you can provide example JSON that exhibits this behavior, I would be happy to help debug.

**Comment by Baransu** [comment]
I'll try to because I have to setup example enviroment and catch JSON coming from server.
Right now we have something like that:  https://youtu.be/9Cjdqqo4OXk

Yellow messages are representing communication to INTERNET node

**Comment by Baransu** [comment]
We're setting `INTERNET` name during data creation. Warnings are representing data coming to `INTERNET`.
https://gist.github.com/Baransu/54c3a51a5af4c35e3c517744a2e6174d

**Comment by Baransu** [comment]
@jrsquared I'm playing with code right now trying to come up with solution for setting up entry node in global view and adding click option for that node. Is it desired behaviour which should be supported?
