### ISSUE TITLE
notices assumes .connection-notice exists

### ISSUE THREAD

**Issue by marianoguerra** [Netflix/vizceral#6]
here https://github.com/Netflix/vizceral/blob/bacb046d5c835b62cca513283aff144cbfb78df6/src/notices.js#L59 and in other places the code operates on noticeElement assuming there is at least a node with the class .connection-notice

one solution is to check if the result of querySelector is defined, the other is to document that it's required to have a tag with that class.

I can provide the patch for this change if you prefer so.

**Comment by marianoguerra** [comment]
wow, that was fast.

thanks!

**Comment by jrsquared** [comment]
Heh, I was already digging around in the code, so it was an easy fix. Thanks for reporting! When refactoring for open source, sometimes it's hard to notice these types of dependencies.
