### ISSUE TITLE
Traffic with no global level (region and focusedChild renders only) breaks focused zoom behavior

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral#60]
This issue was found while following along with the conversation in issue #57, which contains a post that duplicates most of what is here to keep it synced with the conversation that "birthed it", but is a separate issue.  Since, this is to open the issue it has the context needed to reproduce it paraphrased here.

The data format structure shows a `renderer: global` as the top most parent in the traffic data JSON, but apparently this is not required.  You can actually start with a `renderer: region`, which is my desired use case.  That is a `region` which is the parent of a collection of nodes that use `renderer: focusedChild` and the connections between these child nodes (children of the `region`).

When you load and graph a JSON structure that has no global level.... 
---------<begin duplicate content from issue #57 post>-----------
It does kind of work, but there is something crazy happens with event attachments or something.  I took my usual test JSON file which consist of one region, an Internet node and a single connection between them at the global, while the region is has about 30+ nodes interconnected.   I deleted the global render chunk so that only the region node and its children remained.

It graphed just like expected (ltrTree), but none of the child nodes can be zoomed into.  In fact, when I lathered the whole thing up with breakpoints I only get a breakpoint on the single click which opens the details panel, but nothing at all for the double-click that should zoom to the detail level.

**Comment by jrsquared** [comment]
Yep, missed the double click functionality when refactoring to not require specific graph structure. Should be all good to go now. Released 4.3.7 with this fix.

**Comment by jrsquared** [comment]
I just pushed an example json file `sample_data_region_only.json` that should show this working if you just change https://github.com/Netflix/vizceral-example/blob/master/src/components/trafficFlow.jsx#L155
