### ISSUE TITLE
Nodes in global view cannot send and receive data

### ISSUE THREAD

**Issue by singerbj** [Netflix/vizceral#66]
I'm using this for my data:

`
{
                name: 'root',
                renderer: 'global',
                maxVolume: 500,
                nodes: [{
                        name: '1'
                    },
                    {
                        name: '2'
                    }
                ],
                connections: [{
                        source: '1',
                        target: '2',
                        metrics: {
                            normal: 100,
                            warning: 95,
                            danger: 5
                        }
                    },
                    {
                        source: '2',
                        target: '1',
                        metrics: {
                            normal: 100,
                            warning: 95,
                            danger: 5
                        }
                    }
                ]
            }
`

The result is the attached screenshot. Am I doing something wrong?
![capture](https://cloud.githubusercontent.com/assets/3630755/25756861/f52a29dc-318d-11e7-81d6-17f9aa0ada35.PNG)

**Comment by Baransu** [comment]
From version `4.4.0` and above you have to specify `entryNode` property in your top level graph. It's name of your central node on global level. Does it resolve your issue?

**Comment by singerbj** [comment]
Kind of. I'm not getting stats for the nodes other than my entryNode now (I just get the region loading spinner). Is it not possible for all nodes to send and receive data to/from each other?

Also, can you point me at the documentation for entryNode so I can understand it better?

**Comment by singerbj** [comment]
Also why won't this work:
`{
                name: '1',
                renderer: 'global',
                maxVolume: 500,
                entryNode: '1',
                nodes: [{
                        name: '1'
                    },
                    {
                        name: '2'
                    }
                ],
                connections: [{
                        source: '1',
                        target: '2',
                        metrics: {
                            normal: 10,
                            warning: 9,
                            danger: 5
                        }
                    },
                    {
                        source: '2',
                        target: '1',
                        metrics: {
                            normal: 10,
                            warning: 9,
                            danger: 5
                        }
                    }
                ]
            }`

**Comment by aSqrd-eSqrd** [comment]
Your JSON format is dicey at best.  You should take a look at the [Data Format](https://github.com/Netflix/vizceral/wiki/How-to-Use#graph-data-format) wiki.

You can get away with the JSON you have now if you change "global" to "region".  But you are playing a dangerous game by not specifying a `renderer` for each node

**Comment by Baransu** [comment]
Loading region is probably due to no nodes inside your region. I don't know right now how to handle this other than creating some nodes inside region.

I'm afraid there is no documentation about `entryNode`. It's just indicated which node is entry point and central node for your graph. 

What messages are you getting in console regarding your data? What version are you using?
Your problem may be related to no `renderer` specified for every node in global graph.
Try looking [here](https://github.com/Netflix/Vizceral/wiki/How-to-Use) to understand how to use 
vizceral.

**Comment by jrsquared** [comment]
Yes, as @Baransu said, the global graph has an [assumption](https://github.com/Netflix/vizceral/blob/master/src/global/globalNode.js#L37) that nodes will have children nodes. There is currently no way around this, but should be trivial to add something to allow for this. I would be happy to look at a PR around this.

And yes, you have to specify an entryNode or have a node named 'INTERNET'. I updated [the wiki](https://github.com/Netflix/vizceral/wiki/How-to-Use#graph-data-format) to include this.

**Comment by Baransu** [comment]
@jrsquared actually `INTERNET` is assumed on region level not global. On global you have to specify it mandatory. Should we add it for global level graph too?

**Comment by jrsquared** [comment]
Ah, you are correct. No, that's fine.
