### ISSUE TITLE
filterGraph's getNode assumes all nodes have a nodes array attribute

### ISSUE THREAD

**Issue by marianoguerra** [Netflix/vizceral#7]
here https://github.com/Netflix/vizceral/blob/bacb046d5c835b62cca513283aff144cbfb78df6/src/base/trafficGraph.js#L97

one solution would be to document that it's required, the other to check that node.nodes is an array.

the data here https://github.com/Netflix/vizceral-example/blob/master/src/sample_data.json seems to have some nodes withouth a nodes attribute and on click it throws an error.

**Comment by jrsquared** [comment]
Fixed with commit 75b91f3
