### ISSUE TITLE
How to save relative position of nodes if changed by user?

### ISSUE THREAD

**Issue by gupta1** [Netflix/vizceral#70]
Hello!

I have a question regarding the positioning of nodes. Suppose, someone changes the position of nodes on global or detailed view, is it possible to save the relative position of nodes so that resizing etc keeps the order same? Is it possible to save that state, so that if user reloads the browser it remains same?

Thanks a lot for your help in advance! Vizceral tool is pretty cool and works great for our scenario.

**Comment by jrsquared** [comment]
When you position a node, it sets the position on the graph object itself. `viz.currentGraph` is the reference to the current graph. You could extract all the position information yourself and store it off somewhere, then when you send update the data again, pass in the old position information. Saving position state is outside the scope of this project. If you do end up getting something like this put together though, I would love to see it!

**Comment by gupta1** [comment]
Thanks for the direction Justin! 
I was able to save the positions and change it when the vizceral loads for the first time or when the state changes.

**Comment by jrsquared** [comment]
Awesome. Glad it worked for you!

**Comment by 24thdiv** [comment]
Hi I wan to set the position of nodes fixed. So I want to drag a nodes and set the position. But Can you explain how can I extract all the position information of nodes after dragging and set for further use? I want to do same as you explained by storing position.

**Comment by jrsquared** [comment]
You can do this outside of the vizceral component itself. The graph data is accessible outside the component, and the position data is appended to the nodes themselves. You should be able to add something to save the position data in the chrome outside the vizceral component.

**Comment by 24thdiv** [comment]
Hi, This is my code. I am using vizceral-react. Now I can get the position of the nodes when I click on that by calling objectHighlighted method. Now Once I get all nodes position, I want to set the position on each nodes. My nodes details are in "trafficData" variable. My question is, Is there any parameter in nodes like x=200 and y=300 so that I fill this values?

`class App extends Component {

   constructor() {
      super();
       this.state={
          trafficData:nodes,
          allowDraggingOfNodes:true
        }
        this.objectHighlighted.bind(this);

   }

   objectHighlighted(data){
    console.log(data);
   }

  render() {
    console.log(this.state.trafficData);
    return (
      <div className="App" style={{height:800}}>
        <Vizceral traffic={this.state.trafficData}
                  allowDraggingOfNodes={this.state.allowDraggingOfNodes}
                  objectHighlighted={this.objectHighlighted}
        />
      </div>
    );
  }
}
`

**Comment by 24thdiv** [comment]
Hi, This is my code. I am using vizceral-react. Now I can get the position of the nodes when I click on that by calling objectHighlighted method. Now Once I get all nodes position, I want to set the position on each nodes. My nodes details are in "trafficData" variable. My question is, Is there any parameter in nodes like x=200 and y=300 so that I fill this values?


```
class App extends Component {

   constructor() {
      super();
       this.state={
          trafficData:nodes,
          allowDraggingOfNodes:true
        }
        this.objectHighlighted.bind(this);

   }

   objectHighlighted(data){
    console.log(data);
   }

  render() {
    console.log(this.state.trafficData);
    return (
      <div className="App" style={{height:800}}>
        <Vizceral traffic={this.state.trafficData}
                  allowDraggingOfNodes={this.state.allowDraggingOfNodes}
                  objectHighlighted={this.objectHighlighted}
        />
      </div>
    );
  }
} 

```

**Comment by jrsquared** [comment]
Yes, you should be able to put the position data in the same location you got it from.

**Comment by 24thdiv** [comment]
I am not able to set when I give position object in nodes. Can you give me example? It would be really helpful

**Comment by 24thdiv** [comment]
@gupta1 Can you explain me how did you do this?

**Comment by carte7000** [comment]
Hi @24thdiv, to change the position of a node you can do like so

>    const node = vizceral.getNode(['yournodename']);
>       node.updatePosition({
>         x: 120,
>         y: 120,
>       });

Hope this help

**Comment by liam-lai** [comment]
@24thdiv 
I used this way to fix position, change layout and put position into metadata
```
"layout": "ring",
      "nodes": [
        { "name": "node1", "node_type": "user", "renderer": "focusedChild", "class": "danger", "metadata": { "position": { "x": -1000, "y": 0 } } },
        { "name": "node2", "node_type": "service", "renderer": "focusedChild", "metadata": { "position": { "x": -500, "y": -500 } } },
        { "name": "node3", "node_type": "service", "renderer": "focusedChild", "metadata": { "position": { "x": 0, "y": 500 } } },
...
```
