### ISSUE TITLE
event api for mouseover

### ISSUE THREAD

**Issue by opavader** [Netflix/vizceral#73]
Even though `connection` & `node` are getting visually highlighted on `mouseover` but there is no event API to capture it. 
Can the same be also included in `objectHighlighted` or in a new API ?

**Comment by jrsquared** [comment]
Yeah, would make sense as a new event, maybe `objectHovered` or something?

**Comment by opavader** [comment]
@jrsquared Please review & merge https://github.com/Netflix/vizceral/pull/75 if it's as per your expectation.
