### ISSUE TITLE
Is there a way to keep moving nodes inside the canvas boundaries?

### ISSUE THREAD

**Issue by gupta1** [Netflix/vizceral#77]
I am trying to make the moving nodes not go beyond the canvas width and height. I initially thought I can restrict the node position to be in this boundary {-canvas.width/2, canvas.width/2} and {-canvas.height/2, canvas.height/2} but the position of nodes seem different than what I expected. 

Can someone please guide me on how should I proceed? I tried using this.vizceral.currentGraph.layoutDimensions, but looks like this is also not the right dimensions for full canvas. Where are the correct the height and width dimension of vizceral stored which can be used to create canvas boundary?

Thanks

**Comment by gupta1** [comment]
Currently this is what I am doing in moveNodeInteraction.js:
This creates a boundary around the canvas but as you resize the vizceral window, its doesnt always takes the shape of resized window. Any suggestions are welcome. 

  onDocumentMouseMove (event) {
    if (this._state === 1) {
      if (this._lastMBPress_pressedObj_isDraggable) {
        const mouseLocVPSpace = new Vector2(0, 0);
        getMouseLocInVPSpace(event, mouseLocVPSpace);
        const tx = mouseLocVPSpace.x - this._lastMBPress_mouseLocInVPSpace.x;
        const ty = mouseLocVPSpace.y - this._lastMBPress_mouseLocInVPSpace.y;
        const t = doubleSqrt((tx * tx) + (ty * ty));
        if (t > 10) {
          this._onDragStart();
        }
      }
    } else if (this._state === 2) {
      this.vizceral.validateRaycaster(event.clientX, event.clientY);
      const o = this.vizceral.raycaster.ray.origin;
	  var layoutWidth  =  this.vizceralthis.vizceral.currentGraph.layoutDimensions.width;
	  var layoutHeight = this.vizceralthis.vizceral.currentGraph.layoutDimensions.height;
	  var xBound = {left: -layoutWidth/2, right: layoutWidth/2};
	  var yBound = {bottom: -layoutHeight/2, top: layoutHeight/2};
	  var mouseLocX = this._lastMBPress_mouseLocInGraphSpace.x;
	  var mouseLocY = this._lastMBPress_mouseLocInGraphSpace.y;
      const dx = o.x - this._lastMBPress_mouseLocInGraphSpace.x;
      const dy = o.y - this._lastMBPress_mouseLocInGraphSpace.y;
      var newX = this._lastMBPress_pressedObj_pos.x + dx;
      var newY = this._lastMBPress_pressedObj_pos.y + dy;	
	  
	  if (newX > xBound.right || newX < xBound.left)
	  {
		if( newX >= xBound.right){
			newX = xBound.right;
		  }
		  if(newX <= xBound.left){
			newX = xBound.left;
		  }
	  }
	  
	  if (newY > yBound.top || newY < yBound.bottom)
	  {
		  if( newY >= yBound.top){
			newY = yBound.top;
		  }
		  if(newY <= yBound.bottom){
			newY = yBound.bottom;
		  }
	  }
	  
      this._setDraggableObjectPosition(this._lastMBPress_pressedObj, newX, newY);
    }
  }

Thanks a lot for your help!

**Comment by jrsquared** [comment]
We do not use the particle positioning physics internally , and since the developer of it, @jbrekelmans, has not been active here for some time, I'm going to close this. However, I will happily review a PR that would modify this behavior.
