### ISSUE TITLE
[FEATURE] customize a specific node

### ISSUE THREAD

**Issue by javafuns** [Netflix/vizceral#79]
Is it possible to customize a specific node css style ?
For example, INTERNET node is special, so I would like it to be more apparent.

**Comment by jrsquared** [comment]
Not at this time no. However, I would definitely welcome a PR that would allow you to set custom styles on things. Since the nodes are drawn using threejs and not CSS, it would probably be quite difficult though.

**Comment by anrub** [comment]
I found, that you can define - maybe that is enough - your own color of a node, by specifing `styles` at the Vizceral tag and fill it with: `this.styles = {colorTraffic: {myComponent: 'rgb(255, 0,0)'}};` then the "class" attribute in the graph-backing JSON of the node needs to be "myComponent" - then the node gets another color. Just like "warning" or "danger"
