### ISSUE TITLE
ObjectHovered event not getting triggered

### ISSUE THREAD

**Issue by ankit12355** [Netflix/vizceral#86]
Hey Guys 
I was trying to implement Vizceral with angular 4 but ran into a problem when the objecthovered event api call is not being invoked. From the commits it seems the code was added a few months ago, but for some reason its not getting triggered. As a sidenote all the other events are generated fine. 
Anyone else facing this issue?
Thanks
Ankit

**Comment by ankit12355** [comment]
Closing this. Was able to fix it.

**Comment by jrsquared** [comment]
Awesome. Glad you were able to get it figured out!

**Comment by manico** [comment]
> Closing this. Was able to fix it.

@ankit12355 Could you share how did you managed to consume this event?
I seem to be having problem wiring up this event.
