### ISSUE TITLE
Traffic from one region to the other

### ISSUE THREAD

**Issue by ledor473** [Netflix/vizceral#88]
Is there any plan to visualize the non-Internet traffic going from one region to another? 
The global view is nice to visualize something that could be described as "north-south" traffic (traffic from Internet getting redistributed to another region by something outside like a CDN/DNS), but what I'm looking for is a way to visualize "east-west" traffic.
The scenario would be that some service could have fallback in another region if the local one is unresponsive.

I'm thinking about something that looks like the regional view, but that would only show services that interact with another region. Maybe showing services of region 1 on the left and region 2 on the right?

I tried to find a way to do that right now, but maybe that's not a usecase you had to tackle.

Thanks!

**Comment by ledor473** [comment]
After digging a bit more, it seems that we can display inter-region traffic:
https://github.com/Netflix/vizceral-example/blob/master/src/sample_data.json#L8653-L8690
But I dont think we can drilldown on that traffic as of now.

One workaround could be to have a fake region name `us-east-1 <-> us-west-2` (with a different node display), store the direction of the traffic in the node and add a filter on the direction.

**Comment by jrsquared** [comment]
Yeah, this is not a use case that we've ever had to tackle. There is no concept in vizceral of 'inter-region traffic'. It's probably something that you can just create a new graph structure and pass it in. If one of the existing layouts do not work, it would just need a different layout to make it work.
