### ISSUE TITLE
Documentation custom classes on node is incorrect

### ISSUE THREAD

**Issue by fervanrijswijk** [Netflix/vizceral#90]
In the documentation (https://github.com/Netflix/Vizceral/wiki/How-to-Use) the following is stated:

> The class of the node. will default to 'normal' if not provided. The coloring of the UI is based on 'normal', 'warning', and 'danger', so if you want to match the UI coloring, use those class names. Any class you provide will expect to have a style 'colorClassName' available, e.g. if the class is 'fuzzy', you should also call 'vizceral.updateStyles({ colorFuzzy: '#aaaaaa' })'

This will not work. What works is 

`vizceral.updateStyles({ colorTraffic: {fuzzy: '#ff0000'}})`

**Comment by jrsquared** [comment]
Fixed the wiki page. Thank you!
