### ISSUE TITLE
vizceral nod_module build issue

### ISSUE THREAD

**Issue by prabhurangan** [Netflix/vizceral#97]
npm run build:js

> vizceral@4.3.8 build:js /opensource/vizceral-example/node_modules/vizceral
> webpack --bail && webpack --bail -p

Hash: 4b7e17546eabf6279017
Version: webpack 1.15.0
Time: 88ms
          Asset     Size  Chunks             Chunk Names
    vizceral.js  31.7 kB       0  [emitted]  main
vizceral.js.map  36.2 kB       0  [emitted]  main
    + 1 hidden modules
Hash: e6304a35cf944a95ce14
Version: webpack 1.15.0
Time: 100ms
          Asset     Size  Chunks             Chunk Names
vizceral.min.js  31.7 kB       0  [emitted]  main
    + 1 hidden modules

ERROR in vizceral.min.js from UglifyJs
SyntaxError: Unexpected token: name (_) [./src/vizceral.js:18,0]

**Comment by jrsquared** [comment]
You can't run `npm run build:js` from the installed package in `node_modules`. If you clone this repo directly and run `npm run build:js` it should run just fine.
